# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Golang CI test

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Test
      run: go test -v ./...
